"""empty message

Revision ID: 044306fb85a4
Revises: 0d8d7d7dc8bf
Create Date: 2024-06-10 18:56:30.310278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '044306fb85a4'
down_revision: Union[str, None] = '0d8d7d7dc8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_user')
    op.add_column('users', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('voice_status', sa.Enum('disconnected', 'muted', 'unmuted', 'deafened', name='voicestatus'), nullable=True))
    op.add_column('users', sa.Column('video_status', sa.Enum('disconnected', 'camera', 'screen', name='videostatus'), nullable=True))
    op.add_column('users', sa.Column('coordinates', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('screenshare_coordinates', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('screenshare_size', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('video_coordinates', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('video_size', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'users', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'video_size')
    op.drop_column('users', 'video_coordinates')
    op.drop_column('users', 'screenshare_size')
    op.drop_column('users', 'screenshare_coordinates')
    op.drop_column('users', 'coordinates')
    op.drop_column('users', 'video_status')
    op.drop_column('users', 'voice_status')
    op.drop_column('users', 'room_id')
    op.create_table('room_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('voice_status', postgresql.ENUM('disconnected', 'muted', 'unmuted', 'deafened', name='voicestatus'), autoincrement=False, nullable=True),
    sa.Column('video_status', postgresql.ENUM('disconnected', 'camera', 'screen', name='videostatus'), autoincrement=False, nullable=True),
    sa.Column('coordinates', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('screenshare_coordinates', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('screenshare_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('video_coordinates', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('video_size', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='room_user_room_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='room_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='room_user_pkey')
    )
    # ### end Alembic commands ###
