"""empty message

Revision ID: 0d8d7d7dc8bf
Revises: 38d61a4b3bbd
Create Date: 2024-06-10 15:06:43.035162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8d7d7dc8bf'
down_revision: Union[str, None] = '38d61a4b3bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('state', sa.String(length=255), nullable=True))
    op.add_column('activities', sa.Column('event_id', sa.String(length=255), nullable=False))
    op.alter_column('activities', 'event_type',
               existing_type=sa.VARCHAR(length=4096),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'event_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=False)
    op.drop_column('activities', 'event_id')
    op.drop_column('activities', 'state')
    # ### end Alembic commands ###
