"""empty message

Revision ID: 1d29b0ba0f00
Revises: 826d4f9395c3
Create Date: 2024-05-30 14:53:58.656002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d29b0ba0f00'
down_revision: Union[str, None] = '826d4f9395c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('landing_spot', sa.String(length=31), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'landing_spot')
    # ### end Alembic commands ###
