"""empty message

Revision ID: 9be1feb8eaa4
Revises: fbe38fb1ef7b
Create Date: 2024-06-01 17:39:01.727332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be1feb8eaa4'
down_revision: Union[str, None] = 'fbe38fb1ef7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'reply_to',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('messages_reply_to_fkey', 'messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('messages_reply_to_fkey', 'messages', 'messages', ['reply_to'], ['id'])
    op.alter_column('messages', 'reply_to',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
