"""empty message

Revision ID: 9e84d71e36cb
Revises: 4ea7a04b1126
Create Date: 2024-05-25 12:09:39.964890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e84d71e36cb'
down_revision: Union[str, None] = '4ea7a04b1126'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('status', sa.String(length=31), nullable=True))
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=63),
               nullable=True)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('default', name='role'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=63),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'status')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
