"""empty message

Revision ID: bd282a641b82
Revises: 
Create Date: 2024-06-30 11:09:48.184534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd282a641b82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('room_user')
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('rooms', 'password',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    op.alter_column('rooms', 'landing_spot',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('users', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('voice_status', sa.Enum('disconnected', 'muted', 'unmuted', 'deafened', name='voicestatus'), nullable=True))
    op.add_column('users', sa.Column('video_status', sa.Enum('disconnected', 'camera', 'screen', name='videostatus'), nullable=True))
    op.add_column('users', sa.Column('coordinates', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('screenshare_coordinates', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('screenshare_size', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('video_coordinates', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('video_size', sa.String(length=100), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    op.create_foreign_key(None, 'users', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    op.drop_column('users', 'video_size')
    op.drop_column('users', 'video_coordinates')
    op.drop_column('users', 'screenshare_size')
    op.drop_column('users', 'screenshare_coordinates')
    op.drop_column('users', 'coordinates')
    op.drop_column('users', 'video_status')
    op.drop_column('users', 'voice_status')
    op.drop_column('users', 'room_id')
    op.alter_column('rooms', 'landing_spot',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('rooms', 'password',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('room_user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('voice_status', postgresql.ENUM('disconnected', 'muted', 'unmuted', 'deafened', name='voicestatus'), autoincrement=False, nullable=False),
    sa.Column('video_status', postgresql.ENUM('disconnected', 'camera', 'screen', name='videostatus'), autoincrement=False, nullable=False),
    sa.Column('coordinates', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('screenshare_coordinates', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('screenshare_size', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('video_coordinates', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('video_size', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='room_user_room_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='room_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='room_user_pkey')
    )
    op.drop_table('activities')
    # ### end Alembic commands ###
